export default {
  "4-4-2": [
    { position: "gk", player: {} },
    { position: "cb1", player: {} },
    { position: "cb2", player: {} },
    { position: "lb", player: {} },
    { position: "rb", player: {} },
    { position: "cm1", player: {} },
    { position: "cm2", player: {} },
    { position: "cm3", player: {} },
    { position: "dm", player: {} },
    { position: "cf1", player: {} },
    { position: "cf2", player: {} },
  ],
  "4-1-3-2": [
    { position: "gk", player: {} },
    { position: "cb1", player: {} },
    { position: "cb2", player: {} },
    { position: "lb", player: {} },
    { position: "rb", player: {} },
    { position: "lm", player: {} },
    { position: "rm", player: {} },
    { position: "dm", player: {} },
    { position: "am", player: {} },
    { position: "cf1", player: {} },
    { position: "cf2", player: {} },
  ],
  "4-3-3": [
    { position: "gk", player: {} },
    { position: "cb1", player: {} },
    { position: "cb2", player: {} },
    { position: "lb", player: {} },
    { position: "rb", player: {} },
    { position: "cm5", player: {} },
    { position: "cm4", player: {} },
    { position: "cf", player: {} },
    { position: "dm", player: {} },
    { position: "lw", player: {} },
    { position: "rw", player: {} },
  ],
  "4-2-1-3": [
    { position: "gk", player: {} },
    { position: "cb1", player: {} },
    { position: "cb2", player: {} },
    { position: "lb", player: {} },
    { position: "rb", player: {} },
    { position: "cm2", player: {} },
    { position: "dm", player: {} },
    { position: "am", player: {} },
    { position: "cf", player: {} },
    { position: "lw", player: {} },
    { position: "rw", player: {} },
  ],
  "4-2-2-2": [
    { position: "gk", player: {} },
    { position: "cb1", player: {} },
    { position: "cb2", player: {} },
    { position: "lb", player: {} },
    { position: "rb", player: {} },
    { position: "rm", player: {} },
    { position: "lm", player: {} },
    { position: "cm4", player: {} },
    { position: "cm5", player: {} },
    { position: "cf1", player: {} },
    { position: "cf2", player: {} },
  ],
  "5-3-2": [
    { position: "gk", player: {} },
    { position: "cb3", player: {} },
    { position: "cb4", player: {} },
    { position: "cb5", player: {} },
    { position: "lb", player: {} },
    { position: "rb", player: {} },
    { position: "dm", player: {} },
    { position: "cm4", player: {} },
    { position: "cm5", player: {} },
    { position: "cf1", player: {} },
    { position: "cf2", player: {} },
  ],
  "3-3-2-2": [
    { position: "gk", player: {} },
    { position: "cb3", player: {} },
    { position: "cb4", player: {} },
    { position: "cb5", player: {} },
    { position: "dm", player: {} },
    { position: "cm4", player: {} },
    { position: "cm5", player: {} },
    { position: "lm", player: {} },
    { position: "rm", player: {} },
    { position: "cf1", player: {} },
    { position: "cf2", player: {} },
  ],
};
